Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  UserName: root
  Password: sobey@2018
  Host: bj-cdb-02ul8qwa.sql.tencentcdb.com:61504
  DBName: spider-material
  Charset: utf8